# Generated by Django 5.0.3 on 2024-03-24 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MeterValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=10)),
                ('phase', models.CharField(max_length=1)),
            ],
        ),
    ]
